import { ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { CANDIDATE_CODE } from '../constants/config';
import { PrimaryButton } from '../components/PrimaryButton';
import { Palette, ThemeMode } from '../theme/colors';
import { PendingDeletion, Task } from '../types/task';

export function SettingsScreen({ tasks, pendingDeletions, colors, theme, demoNotifications, isOnline, isSyncing, onThemeChange, onDemoChange, onSyncNow }: { tasks: Task[]; pendingDeletions: PendingDeletion[]; colors: Palette; theme: ThemeMode; demoNotifications: boolean; isOnline: boolean; isSyncing: boolean; onThemeChange: (value: ThemeMode) => void; onDemoChange: (value: boolean) => void; onSyncNow: () => void }) {
  const pending = tasks.filter((task) => task.syncStatus !== 'synced').length + pendingDeletions.length;
  return <ScrollView style={styles.flex} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <Text style={[styles.title, { color: colors.text }]}>Settings</Text><Text style={[styles.subtitle, { color: colors.textMuted }]}>Personalize the workspace and manage offline data.</Text>
    <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.cardTitle, { color: colors.text }]}>Appearance</Text><Text style={[styles.cardText, { color: colors.textMuted }]}>Choose a readable theme for working in the field.</Text><View style={styles.themeRow}><PrimaryButton label="Light" onPress={() => onThemeChange('light')} colors={colors} variant={theme === 'light' ? 'primary' : 'ghost'} style={styles.themeButton} /><PrimaryButton label="Dark" onPress={() => onThemeChange('dark')} colors={colors} variant={theme === 'dark' ? 'primary' : 'ghost'} style={styles.themeButton} /></View></View>
    <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.row}><View style={styles.rowCopy}><Text style={[styles.cardTitle, { color: colors.text }]}>Demo reminder mode</Text><Text style={[styles.cardText, { color: colors.textMuted }]}>Schedule a test notification after 45 seconds instead of 30 minutes.</Text></View><Switch accessibilityLabel="Toggle demo reminder mode" value={demoNotifications} onValueChange={onDemoChange} trackColor={{ false: colors.border, true: colors.primary }} /></View></View>
    <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.cardTitle, { color: colors.text }]}>Offline sync</Text><Text style={[styles.cardText, { color: colors.textMuted }]}>{isOnline ? `${pending} task${pending === 1 ? '' : 's'} awaiting mock-server sync.` : 'You are offline. Create, edit, view, and delete tasks normally; changes are queued safely on this device.'}</Text><PrimaryButton label={isOnline ? 'Sync now' : 'Sync unavailable offline'} onPress={onSyncNow} colors={colors} disabled={!isOnline} loading={isSyncing} style={styles.syncButton} /></View>
    <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.cardTitle, { color: colors.text }]}>Assignment code</Text><Text style={[styles.code, { color: colors.primary, backgroundColor: colors.primarySoft }]}>{CANDIDATE_CODE}</Text><Text style={[styles.cardText, { color: colors.textMuted }]}>Include this code in the app, README, and video demonstration.</Text></View>
    <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.cardTitle, { color: colors.text }]}>Data on this device</Text><Text style={[styles.cardText, { color: colors.textMuted }]}>Tasks and history use AsyncStorage. Attachment metadata is saved so image references can remain visible after restart when the device URI still exists.</Text></View>
  </ScrollView>;
}

const styles = StyleSheet.create({ flex: { flex: 1 }, content: { padding: 18, paddingBottom: 28 }, title: { fontSize: 28, fontWeight: '900' }, subtitle: { fontSize: 14, lineHeight: 20, marginTop: 4, marginBottom: 18 }, card: { borderWidth: 1, borderRadius: 16, padding: 16, marginBottom: 12 }, cardTitle: { fontSize: 16, fontWeight: '900' }, cardText: { fontSize: 13, lineHeight: 19, marginTop: 6 }, themeRow: { flexDirection: 'row', gap: 10, marginTop: 15 }, themeButton: { flex: 1 }, row: { flexDirection: 'row', gap: 14, alignItems: 'center' }, rowCopy: { flex: 1 }, syncButton: { marginTop: 15 }, code: { alignSelf: 'flex-start', overflow: 'hidden', borderRadius: 8, paddingHorizontal: 10, paddingVertical: 7, marginTop: 12, fontSize: 16, fontWeight: '900', letterSpacing: 0.6 }, });
